'use client';

import Link from 'next/link';
import {useOperations} from '@/components/operations-provider';
import {PageTitle} from '@/components/ui';
import {CsvImporter} from '@/components/csv-importer';
import {companyProfile} from '@/data/company-profile';
import {OdooIntegrationCard} from '@/components/odoo-integration-card';
import {AuditLogView} from '@/components/audit-log-view';
import {AccountManagementCard} from '@/components/account-management-card';

const euro=(value:number)=>new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(value);

export default function Instellingen(){
  const {reset,mode,canEdit,canAdmin,syncState,session,ready}=useOperations(),policy=companyProfile.commercialPolicy;
  const modeLabel=!ready?'wordt veilig geladen':mode==='database'?'centrale database-stand':mode==='demo'?'afgeschermde demo-stand':'onbeschikbare stand';
  const modeBadge=!ready?'laden':mode;
  if (ready && !canAdmin) return <div className="container-page max-w-3xl"><PageTitle eyebrow="Beheerderstoegang" title="Instellingen zijn afgeschermd" description="Accounts, integraties en databeheer zijn alleen beschikbaar voor de portalbeheerder."/><div className="card p-6"><p className="text-sm leading-6 text-slate-600">Operationele bedrijfsregels blijven zichtbaar op de pagina’s waar ze worden toegepast, zoals Ordervrijgave en Intern of 3PL.</p><Link href="/" className="mt-5 inline-block rounded-xl bg-navy px-4 py-2.5 text-sm font-bold text-white">Terug naar overzicht</Link></div></div>;
  return <div className="container-page max-w-5xl"><PageTitle eyebrow="Beheer" title="Instellingen & bedrijfsregels" description="Beheer beveiliging, opslag, integraties en de vastgelegde operationele en commerciële uitgangspunten."/><nav aria-label="Instellingengroepen" className="mb-5 flex gap-2 overflow-x-auto pb-1">{[['Status','portalstatus'],['Accounts','accounts'],['Integraties','integraties'],['Bedrijfsregels','regels'],['Databeheer','data']].map(([label,id])=><a href={`#${id}`} key={id} className="whitespace-nowrap rounded-full border bg-white px-4 py-2 text-xs font-bold text-slate-700">{label}</a>)}</nav><div className="space-y-5">
    <div id="portalstatus" className="scroll-mt-28"><section className="card p-6"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><h2 className="text-lg font-bold text-navy">Portalstatus</h2><p className="mt-2 text-sm leading-6 text-slate-600">Aangemeld als <b>{session?.displayName}</b> met rol <b>{session?.role}</b> binnen tenant <b>{session?.tenantId}</b>. Opslag <b>{modeLabel}</b>; synchronisatie: <b>{syncState}</b>.</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${mode === 'database' ? 'bg-emerald-50 text-emerald-800' : 'bg-amber-50 text-amber-800'}`}>{modeBadge}</span></div><div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><b>Volume: circa {companyProfile.annualVolume.value.toLocaleString('nl-NL')} per jaar</b><p className="mt-1 leading-6">{companyProfile.annualVolume.note}</p></div></section></div>
    <div id="accounts" className="scroll-mt-28"><AccountManagementCard /></div>
    <div id="integraties" className="scroll-mt-28"><OdooIntegrationCard /></div>
    <section className="card p-6"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 className="text-lg font-bold text-navy">Inco Assist</h2><p className="mt-2 text-sm leading-6 text-slate-600">Assistent over zendingen, relaties, planning, acties, ordervrijgave, voorraad, SOP’s en de keuze intern versus 3PL. Voorstellen worden nooit automatisch uitgevoerd: iedere wijziging vraagt eerst bevestiging van het aangemelde account.</p></div><Link href="/copilot" className="rounded-xl bg-navy px-4 py-2.5 text-sm font-bold text-white">Open Inco Assist</Link></div><p className="mt-4 rounded-xl bg-slate-50 p-3 text-xs leading-5 text-slate-500">Operationele antwoorden gebruiken vaste portalbronnen; voorgestelde wijzigingen worden pas na een expliciete bevestiging opgeslagen.</p></section>
    <div id="regels" className="scroll-mt-28"><section className="card p-6"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 className="text-lg font-bold text-navy">Commerciële vrijgave</h2><p className="mt-2 text-sm text-slate-600">Voorlopige minimumregels uit de ingevulde vragenlijst; bevestig de definitieve berekeningsgrondslag vóór Odoo-writeback.</p></div><Link href="/ordercheck" className="rounded-xl bg-navy px-4 py-2.5 text-sm font-bold text-white">Open Ordervrijgave</Link></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><Rule value={euro(policy.minimumOrderValueExw)} label="Minimum EXW"/><Rule value={euro(policy.dapExceptionMinimumOrderValue)} label="DAP alleen bij uitzondering"/><Rule value={`${policy.minimumNetMarginPercentage}% + ${euro(policy.minimumNetProfitPerOrder)}`} label="Nettomarge + nettowinst"/></div><p className="mt-4 text-xs leading-5 text-slate-500">De exacte kostenopbouw van nettomarge en nettowinst en de regel voor overige Incoterms staan nog open.</p></section></div>
    <section className="card p-6"><h2 className="text-lg font-bold text-navy">Leverancier en productdata</h2><div className="mt-4 grid gap-5 md:grid-cols-2"><div><p className="text-sm font-bold text-slate-700">Leveranciersvoorkeur</p><p className="mt-2 text-sm leading-6 text-slate-600">Directe fabrikant, bij voorkeur {companyProfile.supplierPolicy.preferredPaymentTermDays} dagen betalingstermijn en {companyProfile.supplierPolicy.preferredDeliveryCondition.toLowerCase()}. Een alternatief moet een medische groothandel zijn en op de website merken tonen die Inco-Source al inkoopt.</p></div><div><p className="text-sm font-bold text-slate-700">Verplichte productvelden</p><div className="mt-2 flex flex-wrap gap-2">{companyProfile.requiredProductData.map(x=><span key={x} className="rounded-lg bg-blue-50 px-2.5 py-1 text-xs font-semibold text-blue-800">{x}</span>)}</div></div></div></section>
    <div id="data" className="scroll-mt-28"><section className="card p-6"><h2 className="text-lg font-bold text-navy">Gegevensopslag en herstel</h2><p className="mt-2 text-sm leading-6 text-slate-600">{!ready ? 'De opslagstatus wordt gecontroleerd.' : mode === 'database' ? 'Operationele gegevens staan centraal per tenant met versiecontrole, row-level security en een server-side auditlog. Maak daarnaast providerback-ups en test herstel periodiek.' : mode === 'demo' ? 'Alleen testdata staat tenantgebonden in deze browser. Deze stand is niet geschikt voor gedeelde of echte bedrijfsgegevens.' : 'Opslag is niet beschikbaar. Wijzigingen zijn geblokkeerd totdat de verbinding is hersteld.'}</p>{ready&&canEdit&&mode!=='unavailable'&&<button onClick={()=>confirm(mode === 'database'?'De centrale startset voor deze tenant terugzetten? De wijziging wordt gelogd.':'De demo opnieuw opbouwen met verse testdata?')&&reset()} className="mt-4 min-h-11 rounded-xl border border-red-200 px-4 py-2 text-sm font-bold text-red-700">{mode === 'database'?'Centrale startset terugzetten':'Demo verversen'}</button>}</section></div>
    <section className="card p-6"><h2 className="text-lg font-bold text-navy">Planning importeren</h2><p className="mb-4 mt-2 text-sm text-slate-600">Importeer activiteiten uit CSV. Zo kan een export uit Odoo of van de logistieke partner worden verwerkt zonder handmatig overtypen.</p><CsvImporter/></section>
    <section className="card p-6"><h2 className="text-lg font-bold text-navy">Overige koppelingsstatus</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{[['Extern magazijn / 3PL','Voorraad, inbound en outbound','Niet gekoppeld'],['E-mail & agenda','Bevestigingen en afspraken','Niet gekoppeld']].map(([name,scope,status])=><div key={name} className="rounded-xl bg-slate-50 p-4"><div className="flex items-center justify-between gap-2"><b className="text-navy">{name}</b><span className="rounded-full bg-slate-200 px-2 py-1 text-[10px] font-bold text-slate-700">{status}</span></div><p className="mt-1 text-xs leading-5 text-slate-500">{scope}</p></div>)}</div></section>
    <AuditLogView />
  </div></div>
}

function Rule({value,label}:{value:string;label:string}){return <div className="rounded-xl bg-slate-50 p-4"><div className="text-xl font-bold text-navy">{value}</div><div className="mt-1 text-xs text-slate-500">{label}</div></div>}
