'use client';

import Link from 'next/link';
import {useOperations} from '@/components/operations-provider';
import {PageTitle} from '@/components/ui';
import {CsvImporter} from '@/components/csv-importer';
import {companyProfile} from '@/data/company-profile';

const euro=(value:number)=>new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(value);

export default function Instellingen(){
  const {reset}=useOperations(),policy=companyProfile.commercialPolicy;
  return <div className="container-page max-w-5xl"><PageTitle eyebrow="Beheer" title="Instellingen & bedrijfsregels" description="Beheer lokale gegevens en zie welke uitgangspunten door Jorn zijn bevestigd."/><div className="space-y-5">
    <section className="card p-6"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><h2 className="text-lg font-bold text-navy">Systemen en omvang</h2><p className="mt-2 text-sm leading-6 text-slate-600"><b>Odoo</b> wordt gebruikt voor orders en facturen, maar de koppeling is voor deze test bewust uitgesteld. Zendingen gebruiken nu een bron-onafhankelijk model dat later zonder herbouw aan Odoo gekoppeld kan worden.</p></div><span className="rounded-full bg-blue-100 px-3 py-1 text-xs font-bold text-blue-800">Odoo-ready</span></div><div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><b>Volume: circa {companyProfile.annualVolume.value.toLocaleString('nl-NL')} per jaar</b><p className="mt-1 leading-6">{companyProfile.annualVolume.note}</p></div></section>
    <section className="card p-6"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 className="text-lg font-bold text-navy">Inco Assist</h2><p className="mt-2 text-sm leading-6 text-slate-600">Read-only chat over zendingen, relaties, planning, acties, orderchecks, voorraad, SOP’s en de keuze intern versus 3PL. Standaardmodel: <b>GPT-5.6 Luna</b>. Zonder server-side API-sleutel draait een duidelijk gemarkeerde previewmodus.</p></div><Link href="/copilot" className="rounded-xl bg-navy px-4 py-2.5 text-sm font-bold text-white">Open Inco Assist</Link></div><p className="mt-4 rounded-xl bg-slate-50 p-3 text-xs leading-5 text-slate-500">De modelkeuze staat in <code>OPENAI_MODEL</code>. Operationele feiten worden via vaste functies opgehaald; Inco Assist mag in deze versie niets wijzigen of versturen.</p></section>
    <section className="card p-6"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 className="text-lg font-bold text-navy">Commerciële vrijgave</h2><p className="mt-2 text-sm text-slate-600">Minimumregels uit de ingevulde vragenlijst.</p></div><Link href="/ordercheck" className="rounded-xl bg-navy px-4 py-2.5 text-sm font-bold text-white">Open ordercheck</Link></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><Rule value={euro(policy.minimumOrderValueExw)} label="Minimum EXW"/><Rule value={euro(policy.dapExceptionMinimumOrderValue)} label="DAP alleen bij uitzondering"/><Rule value={`${policy.minimumNetMarginPercentage}% + ${euro(policy.minimumNetProfitPerOrder)}`} label="Nettomarge + nettowinst"/></div><p className="mt-4 text-xs leading-5 text-slate-500">De exacte kostenopbouw van nettomarge en nettowinst en de regel voor overige Incoterms staan nog open.</p></section>
    <section className="card p-6"><h2 className="text-lg font-bold text-navy">Leverancier en productdata</h2><div className="mt-4 grid gap-5 md:grid-cols-2"><div><p className="text-sm font-bold text-slate-700">Leveranciersvoorkeur</p><p className="mt-2 text-sm leading-6 text-slate-600">Directe fabrikant, bij voorkeur {companyProfile.supplierPolicy.preferredPaymentTermDays} dagen betalingstermijn en {companyProfile.supplierPolicy.preferredDeliveryCondition.toLowerCase()}. Een alternatief moet een medische groothandel zijn en op de website merken tonen die Inco-Source al inkoopt.</p></div><div><p className="text-sm font-bold text-slate-700">Verplichte productvelden</p><div className="mt-2 flex flex-wrap gap-2">{companyProfile.requiredProductData.map(x=><span key={x} className="rounded-lg bg-blue-50 px-2.5 py-1 text-xs font-semibold text-blue-800">{x}</span>)}</div></div></div></section>
    <section className="card p-6"><h2 className="text-lg font-bold text-navy">Gegevensopslag testversie</h2><p className="mt-2 text-sm leading-6 text-slate-600">Handmatige invoer en testzendingen worden voor deze eerste test uitsluitend in deze browser bewaard. De nieuwe bronmetadata, externe ID’s en connectorcontracten zijn al voorbereid voor latere centrale opslag en Odoo-synchronisatie.</p><button onClick={()=>confirm('Alle lokaal ingevoerde operationele gegevens wissen?')&&reset()} className="mt-4 rounded-xl border border-red-200 px-4 py-2 text-sm font-bold text-red-700">Lokale invoer wissen</button></section>
    <section className="card p-6"><h2 className="text-lg font-bold text-navy">Planning importeren</h2><p className="mb-4 mt-2 text-sm text-slate-600">Importeer activiteiten uit CSV. Zo kan een export uit Odoo of van de logistieke partner worden verwerkt zonder handmatig overtypen.</p><CsvImporter/></section>
    <section className="card p-6"><h2 className="text-lg font-bold text-navy">Voorbereide koppelingen</h2><div className="mt-4 grid gap-3 sm:grid-cols-3">{[['Odoo','Adapter aanwezig · niet geactiveerd'],['Extern magazijn / 3PL','Voorraad, inbound, outbound en historie'],['E-mail & agenda','Bevestigingen, deadlines en afspraken']].map(([name,scope],index)=><div key={name} className="rounded-xl bg-slate-50 p-4"><div className="flex items-center justify-between gap-2"><b className="text-navy">{name}</b>{index===0&&<span className="rounded-full bg-blue-100 px-2 py-1 text-[10px] font-bold text-blue-800">Voorbereid</span>}</div><p className="mt-1 text-xs leading-5 text-slate-500">{scope}</p></div>)}</div><p className="mt-4 text-xs text-slate-500">Koppelingen worden pas geactiveerd na bevestiging van bronvelden, API-toegang en beveiligingsafspraken.</p></section>
  </div></div>
}

function Rule({value,label}:{value:string;label:string}){return <div className="rounded-xl bg-slate-50 p-4"><div className="text-xl font-bold text-navy">{value}</div><div className="mt-1 text-xs text-slate-500">{label}</div></div>}
