'use client';
import {useState} from 'react';
import {useOperations} from '@/components/operations-provider';
import {Empty,PageTitle} from '@/components/ui';
import type {StockMovement} from '@/types/operations';

export default function Bewegingen(){const {data,saveMovement}=useOperations();const [form,setForm]=useState(false);return <div className="container-page"><PageTitle eyebrow="Traceerbaarheid" title="Voorraadbewegingen" description="Ontvangsten, uitleveringen, correcties, retouren en verplaatsingen." action={<button onClick={()=>setForm(true)} className="rounded-xl bg-navy px-5 py-3 font-bold text-white">+ Beweging registreren</button>}/>{data.movements.length?<div className="card overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{['Datum en tijd','Artikel','Type','Aantal','Van','Naar','Referentie','Uitgevoerd door','Opmerking'].map(x=><th className="px-4 py-3" key={x}>{x}</th>)}</tr></thead><tbody>{[...data.movements].sort((a,b)=>b.dateTime.localeCompare(a.dateTime)).map(m=>{const article=data.articles.find(x=>x.id===m.articleId);return <tr key={m.id} className="border-t"><td className="px-4 py-4">{m.dateTime.replace('T',' ')}</td><td className="px-4 font-bold text-navy">{article?.articleNumber||'—'}</td><td className="px-4">{m.type}</td><td className="px-4 font-bold">{m.quantity}</td><td className="px-4">{m.fromLocation}</td><td className="px-4">{m.toLocation}</td><td className="px-4">{m.reference}</td><td className="px-4">{m.performedBy}</td><td className="px-4">{m.notes||'—'}</td></tr>})}</tbody></table></div>:<Empty><div><p className="font-bold text-navy">Nog geen bewegingen geregistreerd</p><p className="mt-1">Registreer alleen een beweging als deze niet automatisch uit Exact Online of het 3PL-portaal komt.</p></div></Empty>}{form&&<MovementForm onClose={()=>setForm(false)} save={saveMovement}/>}</div>}

function MovementForm({onClose,save}:{onClose:()=>void;save:(v:StockMovement)=>void}){const {data}=useOperations();const [v,setV]=useState<StockMovement>({id:crypto.randomUUID(),dateTime:new Date().toISOString().slice(0,16),articleId:data.articles[0]?.id||'',quantity:0,fromLocation:'Amstelveen',toLocation:'Extern magazijn / 3PL',type:'Verplaatsing',reference:'',performedBy:'Jorn / Hidde',notes:''}),[error,setError]=useState('');const submit=(e:React.FormEvent)=>{e.preventDefault();if(!v.articleId||v.quantity<=0||!v.reference||!v.performedBy){setError('Kies een artikel en vul een positief aantal, referentie en uitvoerder in.');return}save(v);onClose()};return <div className="fixed inset-0 z-50 grid place-items-center bg-navy/60 p-4"><form onSubmit={submit} className="w-full max-w-2xl rounded-2xl bg-white p-6"><div className="flex justify-between"><h2 className="text-2xl font-bold text-navy">Voorraadbeweging registreren</h2><button type="button" onClick={onClose} aria-label="Sluiten">×</button></div>{error&&<p className="mt-3 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mt-5 grid gap-4 sm:grid-cols-2"><F label="Datum en tijd"><input type="datetime-local" value={v.dateTime} onChange={e=>setV({...v,dateTime:e.target.value})}/></F><F label="Artikel"><select value={v.articleId} onChange={e=>setV({...v,articleId:e.target.value})}><option value="">Selecteer artikel</option>{data.articles.map(x=><option value={x.id} key={x.id}>{x.articleNumber} · {x.description}</option>)}</select></F><F label="Type"><select value={v.type} onChange={e=>setV({...v,type:e.target.value as StockMovement['type']})}>{['Ontvangst','Uitlevering','Verplaatsing','Correctie','Retour','Beschadiging','Blokkering','Vrijgave','Transport externe opslag','Terughalen externe opslag'].map(x=><option key={x}>{x}</option>)}</select></F><F label="Aantal"><input type="number" min="1" value={v.quantity} onChange={e=>setV({...v,quantity:Number(e.target.value)})}/></F><F label="Van locatie"><input value={v.fromLocation} onChange={e=>setV({...v,fromLocation:e.target.value})}/></F><F label="Naar locatie"><input value={v.toLocation} onChange={e=>setV({...v,toLocation:e.target.value})}/></F><F label="Referentie"><input value={v.reference} onChange={e=>setV({...v,reference:e.target.value})}/></F><F label="Uitgevoerd door"><select value={v.performedBy} onChange={e=>setV({...v,performedBy:e.target.value})}><option>Jorn / Hidde</option><option>Jorn</option><option>Hidde</option></select></F></div><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-xl border px-4 py-2">Annuleren</button><button className="rounded-xl bg-navy px-4 py-2 font-bold text-white">Opslaan</button></div></form></div>}
function F({label,children}:{label:string;children:React.ReactElement}){return <label><span className="mb-1 block text-sm font-bold">{label}</span><span className="[&>*]:w-full [&>*]:rounded-xl [&>*]:border [&>*]:bg-white [&>*]:px-3 [&>*]:py-2">{children}</span></label>}
