'use client';
import {useMemo,useState} from 'react';
import Link from 'next/link';

type Inputs={reference:string;flow:'Kansgestuurd'|'Herhaalhandel';value:number;margin:number;pallets:number;colli:number;minutes:number;days:number;trips:number;weeklyOrders:number;storage:boolean;capacity:boolean;threePlDeadline:boolean;fragile:boolean;critical:boolean;unannounced:boolean;rush:boolean;wrap:boolean};
type Assumptions={hour:number;travelHours:number;car:number;inbound:number;outbound:number;pick:number;internalStorage:number;externalStorage:number;maxPallets:number;maxMinutes:number;maxDays:number;minBenefit:number};
const defaults:Inputs={reference:'',flow:'Kansgestuurd',value:0,margin:20,pallets:1,colli:4,minutes:45,days:2,trips:1,weeklyOrders:10,storage:false,capacity:true,threePlDeadline:true,fragile:false,critical:false,unannounced:false,rush:false,wrap:false};
const initialAssumptions:Assumptions={hour:125,travelHours:.75,car:35,inbound:18,outbound:15,pick:2.25,internalStorage:2.5,externalStorage:.85,maxPallets:2,maxMinutes:60,maxDays:7,minBenefit:75};

export default function Magazijnbeslissing(){
  const [v,setV]=useState(defaults),[a,setA]=useState(initialAssumptions),[saved,setSaved]=useState(false),[showAssumptions,setShowAssumptions]=useState(false);
  const result=useMemo(()=>{
    const internal=(v.minutes/60+.25)*a.hour+v.trips*(a.travelHours*a.hour+a.car)+v.pallets*v.days*a.internalStorage+.06*350;
    const external=v.pallets*a.inbound+a.outbound+v.colli*a.pick+v.pallets*v.days*a.externalStorage+.2*a.hour+.025*400;
    const logicallStorage=v.pallets*Math.max(1,Math.ceil(v.days/7))*2.20;
    const logicallSurcharges=(v.unannounced?19.50+v.pallets*4.95:0)+(v.rush?27.50:0)+(v.wrap?v.pallets*3.09:0);
    const logicall=v.pallets*8.50+v.pallets*5.50+logicallStorage+260/Math.max(1,v.weeklyOrders)+logicallSurcharges;
    const hardFlags=[v.storage?'Structurele opslag nodig':null,!v.capacity?'Interne capaciteit ontbreekt':null,v.pallets>a.maxPallets?'Te veel pallets voor intern':null,v.minutes>a.maxMinutes?'Te veel interne handlingtijd':null,v.days>a.maxDays?'Te lange interne opslag':null,v.critical?'Kritieke product- of traceerbaarheidseisen':null].filter(Boolean) as string[];
    const warnings=[v.fragile?'Kwetsbaar of hoge waarde: extra controle nodig':null].filter(Boolean) as string[];
    const recommendation=!v.threePlDeadline?(hardFlags.length?'Escaleren: geen haalbare standaardroute':'Intern in Amstelveen'):hardFlags.length||internal+a.minBenefit>=external?'Extern magazijn / 3PL':'Intern in Amstelveen';
    return{internal,external,logicall,logicallSurcharges,difference:internal-external,hardFlags,warnings,recommendation,marginValue:v.value*v.margin/100};
  },[v,a]);
  const set=<K extends keyof Inputs>(key:K,value:Inputs[K])=>{setSaved(false);setV(x=>({...x,[key]:value}))};
  const adviceTone=result.recommendation.startsWith('Escaleren')?'bg-amber-600':result.recommendation.startsWith('Extern')?'bg-navy':'bg-emerald-700';
  return <div className="container-page">
    <div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="label">Operationele keuzehulp</p><h1 className="mt-2 text-4xl font-bold text-navy">Intern uitvoeren of extern magazijn / 3PL?</h1><p className="mt-3 max-w-3xl leading-7 text-slate-600">Vergelijk werkelijke kosten, commerciële tijd, capaciteit en risico. Een afwijking van de uitkomst vraagt een gemotiveerd akkoord van de bevoegde beslissers.</p></div><Link href="/sops/sop-007-keuze-intern-magazijn-3pl-en-transfers" className="text-sm font-bold text-accent">Open SOP-007 →</Link></div>
    <div className="mt-7 grid gap-6 xl:grid-cols-[1fr_.78fr]">
      <section className="card p-6"><h2 className="text-lg font-bold text-navy">Gegevens van de goederenstroom</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Referentie"><input value={v.reference} onChange={e=>set('reference',e.target.value)}/></Field><Field label="Handelsstroom"><select value={v.flow} onChange={e=>set('flow',e.target.value as Inputs['flow'])}><option>Kansgestuurd</option><option>Herhaalhandel</option></select></Field><NumberField label="Order-/inkoopwaarde (€)" value={v.value} set={x=>set('value',x)}/><NumberField label="Verwachte brutomarge (%)" value={v.margin} set={x=>set('margin',x)}/><NumberField label="Aantal pallets" value={v.pallets} set={x=>set('pallets',x)}/><NumberField label="Aantal colli" value={v.colli} set={x=>set('colli',x)}/><NumberField label="Interne handlingtijd (minuten)" value={v.minutes} set={x=>set('minutes',x)}/><NumberField label="Opslagduur (dagen)" value={v.days} set={x=>set('days',x)}/><NumberField label="Aantal interne ritten" value={v.trips} set={x=>set('trips',x)}/></div><h3 className="mt-7 font-bold text-navy">Randvoorwaarden</h3><div className="mt-3 grid gap-3 sm:grid-cols-2">{([['storage','Structurele opslag nodig'],['capacity','Interne capaciteit beschikbaar'],['threePlDeadline','3PL kan deadline halen'],['fragile','Kwetsbaar / hoge waarde'],['critical','Batch, lot, houdbaarheid of speciale handling kritisch']] as [keyof Inputs,string][]).map(([key,label])=><label key={key} className="flex items-center justify-between gap-3 rounded-xl border p-3 text-sm font-semibold"><span>{label}</span><input type="checkbox" checked={Boolean(v[key])} onChange={e=>set(key,e.target.checked as never)} className="h-5 w-5 accent-blue-600"/></label>)}</div></section>
      <aside className="space-y-5"><section className={`rounded-3xl p-6 text-white ${adviceTone}`}><p className="text-xs font-bold uppercase tracking-widest opacity-75">Aanbeveling</p><h2 className="mt-3 text-3xl font-bold">{result.recommendation}</h2><p className="mt-3 text-sm leading-6 opacity-90">{result.recommendation.startsWith('Escaleren')?'Noch intern, noch de standaard 3PL-route voldoet. Regel eerst een derde route of nieuwe afspraak.':result.hardFlags.length?'Harde operationele grenzen maken intern uitvoeren onverstandig.':result.recommendation.startsWith('Extern')?'De 3PL is inclusief commerciële tijd aantoonbaar voordeliger.':'Intern blijft binnen de grenzen en is voldoende voordeliger.'}</p></section><section className="card p-5"><h3 className="font-bold text-navy">Kostenvergelijking</h3><div className="mt-4 space-y-3"><Cost label="Totale interne kosten" value={result.internal}/><Cost label="Totale 3PL-kosten" value={result.external}/><Cost label="Intern minus 3PL" value={result.difference} strong/><Cost label="Verwachte brutomarge" value={result.marginValue}/></div><p className="mt-4 text-xs leading-5 text-slate-500">Interne kosten bevatten commerciële tijd, reistijd, autokosten, opslag en verwachte foutkosten.</p></section>{[...result.hardFlags,...result.warnings].length>0&&<section className="card border-amber-200 p-5"><h3 className="font-bold text-amber-900">Aandachtspunten</h3><ul className="mt-3 space-y-2 text-sm text-amber-800">{[...result.hardFlags,...result.warnings].map(x=><li key={x}>• {x}</li>)}</ul></section>}<button onClick={()=>setSaved(true)} className="w-full rounded-xl bg-blue-600 px-5 py-3.5 font-bold text-white">Besluit markeren als besproken</button>{saved&&<p className="rounded-xl bg-emerald-50 p-3 text-center text-sm font-semibold text-emerald-800">Besluit besproken. Leg een afwijkende motivatie vast in de actielijst.</p>}</aside>
    </div>
    <section className="card mt-7 p-6"><button onClick={()=>setShowAssumptions(x=>!x)} className="flex w-full items-center justify-between text-left font-bold text-navy"><span>Rekenaannames beheren</span><span>{showAssumptions?'−':'+'}</span></button>{showAssumptions&&<div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Assumption label="Uurtarief commerciële tijd" value={a.hour} set={x=>setA({...a,hour:x})}/><Assumption label="Rijtijd per rit (uur)" value={a.travelHours} set={x=>setA({...a,travelHours:x})}/><Assumption label="Autokosten per rit" value={a.car} set={x=>setA({...a,car:x})}/><Assumption label="3PL inbound per pallet" value={a.inbound} set={x=>setA({...a,inbound:x})}/><Assumption label="3PL outbound per order" value={a.outbound} set={x=>setA({...a,outbound:x})}/><Assumption label="3PL pick per colli" value={a.pick} set={x=>setA({...a,pick:x})}/><Assumption label="Max. pallets intern" value={a.maxPallets} set={x=>setA({...a,maxPallets:x})}/><Assumption label="Minimaal voordeel intern" value={a.minBenefit} set={x=>setA({...a,minBenefit:x})}/></div>}<p className="mt-3 text-xs text-slate-500">Vervang deze startwaarden zodra werkelijke interne tijd en 3PL-tarieven beschikbaar zijn.</p></section>
    <section className="card mt-7 p-6"><div className="grid gap-6 lg:grid-cols-3"><Partner label="Huidige 3PL" title="Scan Global Logistics">Beoordeel op werkelijke tarieven, cut-offs, voorraadbetrouwbaarheid, portaalgebruik en afwijkingsafhandeling.</Partner><Partner label="Mogelijke opvolger" title="Logicall Zaandam">Nog geen gekozen partner. Eerst offerte, portal-demo, SLA, testinbound, testorder en medische producthandling bevestigen.</Partner><Partner label="Overstapvoorwaarde" title="Geen migratie op uitstraling alleen">Neem voorraadreconciliatie, implementatie-uren, eenmalige kosten, contract en terugvalscenario mee.</Partner></div></section>
  </div>
}
function Field({label,children}:{label:string;children:React.ReactElement}){return <label><span className="mb-1.5 block text-sm font-bold text-slate-700">{label}</span><span className="[&>*]:w-full [&>*]:rounded-xl [&>*]:border [&>*]:bg-white [&>*]:px-3 [&>*]:py-2.5">{children}</span></label>}
function NumberField({label,value,set}:{label:string;value:number;set:(v:number)=>void}){return <Field label={label}><input type="number" min="0" value={value} onChange={e=>set(+e.target.value)}/></Field>}
function Assumption({label,value,set}:{label:string;value:number;set:(v:number)=>void}){return <NumberField label={label} value={value} set={set}/>}
function Cost({label,value,strong=false}:{label:string;value:number;strong?:boolean}){return <div className={`flex justify-between ${strong?'border-t pt-3 font-bold text-navy':''}`}><span>{label}</span><span>€ {value.toFixed(2)}</span></div>}
function Partner({label,title,children}:{label:string;title:string;children:React.ReactNode}){return <div><p className="label">{label}</p><h3 className="mt-2 font-bold text-navy">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{children}</p>{title==='Logicall Zaandam'&&<LogicallOffer/>}</div>}
function LogicallOffer(){const [pallets,setPallets]=useState(1),[weeks,setWeeks]=useState(1),[weeklyOrders,setWeeklyOrders]=useState(10),[unannounced,setUnannounced]=useState(false),[rush,setRush]=useState(false),[wrap,setWrap]=useState(false);const surcharge=(unannounced?19.50+pallets*4.95:0)+(rush?27.50:0)+(wrap?pallets*3.09:0);const total=pallets*8.50+pallets*5.50+pallets*weeks*2.20+260/Math.max(1,weeklyOrders)+surcharge;return <div className="mt-5 rounded-2xl border border-blue-200 bg-blue-50 p-4"><b className="text-sm text-navy">Offertecalculator 2026</b><div className="mt-3 grid grid-cols-3 gap-2"><MiniInput label="Pallets" value={pallets} set={setPallets}/><MiniInput label="Opslagweken" value={weeks} set={setWeeks}/><MiniInput label="Orders/week" value={weeklyOrders} set={setWeeklyOrders}/></div><div className="mt-3 space-y-2 text-xs"><Check label="Niet aangemelde inslag" value={unannounced} set={setUnannounced}/><Check label="Spoedorder" value={rush} set={setRush}/><Check label="Pallets wikkelen" value={wrap} set={setWrap}/></div><div className="mt-4 flex items-end justify-between border-t border-blue-200 pt-3"><span className="text-xs text-slate-600">Indicatie per goederenstroom</span><b className="text-xl text-navy">€ {total.toFixed(2)}</b></div>{surcharge>0&&<p className="mt-2 text-xs font-bold text-red-700">Waarvan toeslagen: € {surcharge.toFixed(2)}</p>}<p className="mt-3 text-[11px] leading-4 text-slate-500">Offerte 20260254: inslag €8,50, uitslag €5,50, opslag €2,20 per pallet/week en €260 servicefee/week, naar rato verdeeld. Scan Global blijft de huidige 3PL.</p></div>}
function MiniInput({label,value,set}:{label:string;value:number;set:(v:number)=>void}){return <label className="text-[11px] text-slate-600">{label}<input className="mt-1 w-full rounded-lg border bg-white px-2 py-1.5" type="number" min="1" value={value} onChange={e=>set(+e.target.value)}/></label>}
function Check({label,value,set}:{label:string;value:boolean;set:(v:boolean)=>void}){return <label className="flex items-center justify-between"><span>{label}</span><input type="checkbox" checked={value} onChange={e=>set(e.target.checked)}/></label>}
