'use client';
import {useState} from 'react';
import {useOperations} from '@/components/operations-provider';
import {ActivityForm} from '@/components/activity-form';
import {PageTitle} from '@/components/ui';
import {today} from '@/lib/operations';
import type {Partner,PlannedActivity} from '@/types/operations';

export default function Relaties(){const {data,savePartner}=useOperations();const [open,setOpen]=useState(false),[appointment,setAppointment]=useState<Partner|null>(null);const initial=(p:Partner):PlannedActivity=>({id:crypto.randomUUID(),date:today(),startTime:p.usualTime||'09:00',endTime:'10:00',activityType:p.kind==='Leverancier'?'Leverancierslevering':'Ophaling',supplierId:p.kind==='Leverancier'?p.id:undefined,carrierId:p.kind!=='Leverancier'?p.id:undefined,reference:'',description:`Afspraak met ${p.name}`,originLocation:p.location,destinationLocation:'Amstelveen',expectedPallets:0,expectedCases:0,expectedItems:0,responsibleEmployee:'Jorn / Hidde',status:'Verwacht',notes:p.notes,slotConfirmed:false,appointmentContact:p.contactPerson});return <div className="container-page"><PageTitle eyebrow="Operationele contacten" title="Relaties" description="Leveranciers, vervoerders en logistieke partners met contact- en leverafspraken." action={<button onClick={()=>setOpen(true)} className="rounded-xl bg-navy px-5 py-3 font-bold text-white">+ Relatie</button>}/><div className="mb-6 rounded-2xl border border-amber-200 bg-amber-50 p-5"><h2 className="font-bold text-amber-950">Standaard voor iedere levering</h2><p className="mt-1 text-sm leading-6 text-amber-900">Spreek een bloktijd af, laat deze schriftelijk bevestigen en bel vóór het einde van het venster wanneer de chauffeur nog niet onderweg is. “In de ochtend” is geen bruikbare afspraak.</p></div>{data.partners.length?<div className="grid gap-5 lg:grid-cols-2">{data.partners.map(p=><article className="card p-6" key={p.id}><p className="label">{p.kind}</p><div className="mt-1 flex items-start justify-between gap-4"><h2 className="text-xl font-bold text-navy">{p.name}</h2><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">{p.status}</span></div><dl className="mt-5 grid gap-4 text-sm sm:grid-cols-2">{[['Contact',p.contactPerson],['E-mail',p.email],['Telefoon',p.phone],['Dienst',p.service],['Locatie',p.location],['Vaste leverdag',p.usualDays],['Voorkeurstijd',p.usualTime],['Afspraken / escalatie',p.notes]].filter(([,v])=>v).map(([k,v])=><div key={k}><dt className="text-slate-500">{k}</dt><dd className="mt-1 font-semibold">{v}</dd></div>)}</dl><button onClick={()=>setAppointment(p)} className="mt-5 w-full rounded-xl bg-blue-50 px-4 py-3 text-sm font-bold text-accent">Leverafspraak maken</button></article>)}</div>:<Empty onClick={()=>setOpen(true)}/>} {open&&<PartnerForm save={savePartner} close={()=>setOpen(false)}/>} {appointment&&<ActivityForm initial={initial(appointment)} onClose={()=>setAppointment(null)}/>}</div>}
function Empty({onClick}:{onClick:()=>void}){return <div className="card border-dashed p-10 text-center"><h2 className="font-bold text-navy">Nog geen relaties toegevoegd</h2><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-slate-500">Voeg alleen partijen toe die nodig zijn voor bestellen, transport, opslag of escalatie.</p><button onClick={onClick} className="mt-5 rounded-xl bg-navy px-4 py-2.5 text-sm font-bold text-white">Eerste relatie toevoegen</button></div>}
function PartnerForm({save,close}:{save:(v:Partner)=>void;close:()=>void}){const [v,setV]=useState<Partner>({id:crypto.randomUUID(),kind:'Leverancier',name:'',contactPerson:'',email:'',phone:'',service:'',usualDays:'',usualTime:'',location:'',averageVolume:'',notes:'',status:'Actief'});const change=(k:keyof Partner,x:string)=>setV({...v,[k]:x});return <div className="fixed inset-0 z-50 grid place-items-center bg-navy/60 p-4"><form onSubmit={e=>{e.preventDefault();if(v.name.trim()){save(v);close()}}} className="w-full max-w-2xl rounded-2xl bg-white p-6"><div className="flex justify-between"><h2 className="text-2xl font-bold text-navy">Relatie toevoegen</h2><button type="button" onClick={close}>×</button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><F label="Type"><select value={v.kind} onChange={e=>change('kind',e.target.value)}><option>Leverancier</option><option>Transporteur</option><option>Logistieke partner</option></select></F><F label="Naam *"><input value={v.name} onChange={e=>change('name',e.target.value)}/></F><F label="Contactpersoon"><input value={v.contactPerson} onChange={e=>change('contactPerson',e.target.value)}/></F><F label="E-mail"><input type="email" value={v.email} onChange={e=>change('email',e.target.value)}/></F><F label="Telefoon"><input value={v.phone} onChange={e=>change('phone',e.target.value)}/></F><F label="Dienst"><input value={v.service} onChange={e=>change('service',e.target.value)}/></F><F label="Locatie"><input value={v.location} onChange={e=>change('location',e.target.value)}/></F><F label="Vaste leverdag(en)"><input value={v.usualDays} onChange={e=>change('usualDays',e.target.value)}/></F><F label="Voorkeurs-bloktijd"><input type="time" value={v.usualTime} onChange={e=>change('usualTime',e.target.value)}/></F><F label="Afspraken / escalatie"><textarea rows={3} value={v.notes} onChange={e=>change('notes',e.target.value)}/></F></div><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={close} className="rounded-xl border px-4 py-2">Annuleren</button><button className="rounded-xl bg-navy px-4 py-2 font-bold text-white">Opslaan</button></div></form></div>}
function F({label,children}:{label:string;children:React.ReactElement}){return <label><span className="mb-1 block text-sm font-bold">{label}</span><span className="[&>*]:w-full [&>*]:rounded-xl [&>*]:border [&>*]:px-3 [&>*]:py-2.5">{children}</span></label>}
